### ISSUE TITLE
Errors with Modtran files

### ISSUE THREAD

**Issue by CarlosGrohmann** [NelisW/ComputationalRadiometry#2]
Hi, I'm trying to run the notebook 08 (Modtran File Processing), but I can't read the tape7 file. This is the error I'm getting:

---

TypeError                                 Traceback (most recent call last)
<ipython-input-4-2d1c0971b9f3> in <module>()
      1 tape7 = rymodtran.loadtape7("tape7-01", ['FREQ_CM-1', 'COMBIN_TRANS', 
      2                                          'MOLEC_SCAT', 'AER+CLD_TRANS',
----> 3                                          'AER+CLD_abTRNS'] )
      4 print(tape7.shape)

/usr/local/lib/python2.7/site-packages/pyradi/rymodtran.pyc in loadtape7(filename, colspec)
    240     # build a new data set with appropriate column header and numeric data
    241     #change all - and +  to alpha to enable table lookup
--> 242     colHead = fixHeadersList(colHead)
    243 
    244     s = ' '.join(colHead) + '\n'

/usr/local/lib/python2.7/site-packages/pyradi/rymodtran.pyc in fixHeadersList(headcol)
    100     """
    101 
--> 102     headcol = [fixHeaders(str) for str in headcol]
    103     return headcol
    104 

/usr/local/lib/python2.7/site-packages/pyradi/rymodtran.pyc in fixHeaders(instr)
     80         assert isinstance(instr, str)
     81         translate_table = maketrans(intab, outtab)
---> 82     return instr.translate(translate_table)
     83 
     84 

TypeError: expected a character buffer object

I tried it directly on python and also on the notebook. Same error. 

Thanks

**Comment by NelisW** [comment]
Hi Carlos

thanks for trying pyradi.

Some time ago I started to work on dual compatibility with Python 2 and 3
and got stopped halfway by workload elsewhere. your observation could be a
result of this.  can you send me a copy of your tape7 file?  You need not
send all of the lines, just the header and the first five or six lines of
spectral data will be fine.

I can look in to this and report back to you

regards

nelis

**Comment by CarlosGrohmann** [comment]
Hello Nelis

thanks for your quick reply. I'm trying to use the modtran file you provided in the example. (modtrandata.tgz).

best

Carlos

**Comment by NelisW** [comment]
Hi Carlos

I commited the latest version of pyradi, docs and notebooks to github.
I cannot build and upload the pypi (pip install packages) from work, will
do this tonight and let you know when done.

Your email prompts me to get back to the python 2 to 3 port.  Part of the
work is easy and some is really painful, so I shy away from it - but I must
face it and complete the task.

regards

nelis

**Comment by NelisW** [comment]
Latest version on PyPi and  github.
please try again

**Comment by CarlosGrohmann** [comment]
Working! 

many many thanks.

**Comment by NelisW** [comment]
thanks and enjoy.

I am a bit busy lately wth home automation and solar power, but if you have
some need that may be of general value, please let me know so that I can
add this in to pyradi

First on the todo list in pyradi is to work towards simulatneous Python 2
and 3 compliance. , currently only 2.
